In [1]:
import numpy as np

In [7]:
x = np.random.rand(5, 4)
w = np.random.randn(4, 3)
b = np.ones((1, 3))

t = np.zeros((5, 3))
t[0, 0] = 1
t[1, 0] = 1
t[2, 1] = 1
t[3, 1] = 1
t[4, 2] = 1

In [18]:
x

array([[ 0.29908336,  0.37945704,  0.89472331,  0.38217345],
       [ 0.72328712,  0.32062353,  0.62833114,  0.18837291],
       [ 0.0037448 ,  0.98486005,  0.34261161,  0.63043254],
       [ 0.92314189,  0.84778626,  0.72960204,  0.05609937],
       [ 0.86783344,  0.70021305,  0.22975044,  0.52032335]])

In [19]:
w

array([[ 1.50440028,  0.0848374 , -0.39141005],
       [ 1.15324131, -0.25311484, -0.37600665],
       [-0.0050619 , -0.97666011, -1.12697903],
       [ 0.06843028, -0.56640848,  0.85325895]])

In [8]:
def logistic_model(inputs, weights, bias):
    z = np.dot(x, w) + b
    _e = np.exp(z)
    logits = np.divide(_e, np.sum(_e, axis=1, keepdims=True))
    return logits

In [9]:
def ce_loss(output, target):
    return -1.0 * np.mean( np.sum(np.multiply(target, np.log(output)), axis=1) )

In [10]:
output = logistic_model(x, w, b)

In [11]:
ce_loss(output, t)

1.7736380215689749

In [16]:
np.multiply(t, np.log(output))

array([[-0.24937468, -0.        , -0.        ],
       [-0.18148256, -0.        , -0.        ],
       [-0.        , -2.43502123, -0.        ],
       [-0.        , -3.30625066, -0.        ],
       [-0.        , -0.        , -2.69606098]])

In [15]:
np.sum( np.multiply(t, np.log(output)), axis=1 , keepdims=True)

array([[-0.24937468],
       [-0.18148256],
       [-2.43502123],
       [-3.30625066],
       [-2.69606098]])

In [17]:
-np.mean(np.sum( np.multiply(t, np.log(output)), axis=1 , keepdims=True))

1.7736380215689749